name: Release

on:
  push:
    branches: [ master, "feature/cd*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    #- name: Restore dependencies
    #  run: dotnet restore
    #- name: Build
    #  run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish /p:PublishProfile=Release-linux-x64
    - name: Upload DownloadYouTube Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DownloadYouTube-linux-x64
        path: /home/runner/work/YouTuber/YouTuber/Software/linux-x64/
